# Copyright (C) 2019 - 2021 FUJIFILM Italia S.p.A.
# Medical Informatics Research & Development U.it:443
# All Rights Reserved

version: '3'
services:
    be:
        image: payarapostbootbug
        volumes:
            - ./logs:/var/log/payara
            - ./certs:/certs
            - ./config/be/resources:/resources
        ports:
            - 8383:8080

